language: android
jdk: oraclejdk8
sudo: false
android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-29.0.2
        - android-29
        - extra-android-support
        - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-29"

script:
  ./gradlew clean build

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
