name: visiondroid

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build VisionDroid app
        run: ./gradlew build
      - name: Publish VisionDroid apk file
        run: ./CI/build.sh
