name: visiondroid

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Build the app
        run: ./gradlew build

      - name: Publish the app
        run: ./CI/build.sh
